# YAML
INTERNET:
  - device: cisco
  - ip: 192.168.0.200
  - login: admin
  - password: cisco
  - enablepassword: 
  - sleep:  2
  - sh ip cef
  - sh ip cef adjacency
  - sh ip protocol
  - sh ip route vrf Customer9
  - sh ip route
  - sh ip route summary
  - sh ip route connected
  - sh ip route static
  - sh ip vrf
  - sh ip vrf interfaces
  - sh ip vrf detail
  - sh route-map
  - sh run
  - sh adjacency
  - sh adjacency detail
  - sh controllers
  - sh flash
  - sh buffers
  - sh memory summary
  - sh process cpu
  - sh stacks
  - sh cdp neighbors
  - sh key chain