# YAML
IOU3:
  - device: cisco
  - ip: 192.168.0.203
  - login: admin
  - password: cisco
  - enablepassword: 
  - sleep:  2
  - sh ip nhrp
  - sh ip nhrp detail
  - sh ip nhrp nhs
  - sh ip nhrp multicast
  - sh dmvpn
  - sh dmvpn detail
  - sh dmvpn static
  - sh tunnel endpoint tunnel 0
  - sh crypto isakmp policy
  - sh crypto isakmp sa
  - sh crypto isakmp sa detail
  - sh crypto ipsec sa
  - sh ip eigrp neighbors
  - sh ip eigrp neighbors detail
  - sh ip eigrp interfaces
  - sh ip eigrp topology
  - sh ip eigrp traffic
  - sh key chain
  - sh ip cef
  - sh ip cef adjacency
  - sh ip protocol
  - sh ip route vrf Customer9
  - sh ip route
  - sh ip route summary
  - sh ip route connected
  - sh ip route static
  - sh ip vrf
  - sh ip vrf interfaces
  - sh ip vrf detail
  - sh route-map
  - sh run
  - sh adjacency
  - sh adjacency detail
  - sh controllers
  - sh flash
  - sh buffers
  - sh memory summary
  - sh process cpu
  - sh stacks
  - sh cdp neighbors
  - sh key chain
