# YAML
PC6:
  - device: linux
  - ip: 172.17.0.6
  - login: root
  - password: gns3vpc
  - enablepassword: 
  - sleep:  2
  - ping -c3 20.0.0.2
  - ping -c3 30.0.0.3
  - ping -c3 50.0.0.5
  - ping -c3 40.0.0.4
  - ping -c3 70.0.0.7
  - traceroute 20.0.0.2
  - traceroute 30.0.0.3
  - traceroute 50.0.0.5
  - traceroute 40.0.0.4
  - traceroute 70.0.0.7
  - uname -a
  - lsb-release -a
  - ip -4 route show
  - ip -6 route show
  - ip -6 a
  - ifconfig
  - ip -6 neighbor show
  - cat /proc/net/if_inet6
  - sysctl -a
  - free mto
